spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
name: spring-boot-testing-yaml
environment: dev

main:
  lazy-initialization: true
autoconfigure:
  exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

demo:
  environment: 'dev'
  datasource:
    driverClassName: 'oracle.jdbc.OracleDriver'
    url: 'jdbc:oracle:thin:@//localhost:1521/AIB'
    username: 'SpringBoot'
    password: 'password'
